apps:
  - script: build/index.js
    name: 'api-app'
    instances: "max"
    exec_mode: cluster
    env:
      NODE_ENV: development
      APP_MODE: api
      PORT_HTTP: 3001
      PORT_HTTPS: 3000
      MYSQL_HOST: 127.0.0.1
      MYSQL_USER: root
      MYSQL_PASSWORD: Cab230!
      MYSQL_DATABASE: volcanoes

